CREATE TABLE lektori ( -- musi se ta struktura jeste propracovat
	ID INT NOT NULL AUTO_INCREMENT,
	ZKR VARCHAR(25) NOT NULL,
	JMENO VARCHAR(25) NOT NULL,
	PRIJM VARCHAR(50) NOT NULL,
	OBORY VARCHAR(255),
	MISTA VARCHAR(255),
	DOMA CHAR(1) NOT NULL,
	DOJEZD CHAR(1) NOT NULL,
	RANK INT,  -- pocet odpracovanych hodin
	FOTO VARCHAR(50),
	POPIS VARCHAR(255),
	DIPL VARCHAR(255), --duplicita pro zapis skolenych ceritfikatu a znalosti
	REG DATETIME NOT NULL,
	PRIMARY KEY (ID)
);
 

CREATE TABLE obory (
	ID INT NOT NULL AUTO_INCREMENT,
	OBOR VARCHAR(10) NOT NULL,
	NAZEV VARCHAR(25) NOT NULL,
	UROVEN INT NOT NULL,
	POPIS VARCHAR(255),
	PRIMARY KEY (ID)
);

CREATE TABLE lekce (
	ID INT NOT NULL AUTO_INCREMENT,
	ZKR VARCHAR(25) NOT NULL,
	OBOR VARCHAR(10) NOT NULL,
	CAS_OD DATETIME NOT NULL,
	CAS_DO DATETIME NOT NULL,
	FINAL CHAR(1) NOT NULL,
	PRIMARY KEY (ID)
);

	CREATE TABLE login (
	ID INT NOT NULL AUTO_INCREMENT,
	USR VARCHAR(25) NOT NULL,
	PWD VARCHAR(255) NOT NULL,
	HASH VARCHAR(5) NOT NULL,
	PRIMARY KEY (ID)
);
